version: "3"
services:
  hub:
    image: selenium/hub:latest
    ports:
      - "4444:4444"
  chrome:
    image: selenium/node-chrome:latest
    shm_size: '256m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub
  firefox:
    image: selenium/node-firefox:latest
    shm_size: '256m'
    depends_on:
      - hub
    environment:
      - HUB_HOST=hub